# This file was generated by update-test-config
#
compile;pr101624.f90;;-O2 -fsanitize=undefined;
compile;pr106062.f90;;-O2 -fsanitize=undefined;
run;bind-c-intent-out-2.f90;;-fsanitize=undefined -fcheck=all;