# This file was generated by update-test-config
#
compile;pr35154-dwarf2.f;;-dA -gno-strict-dwarf;;
compile;pr37738.f;;-dA -gno-strict-dwarf;;
compile;pr43166.f;;-O;;
compile;pr46756.f;;-O -fcompare-debug;;
compile;trivial.f;;;;