# This file was generated by update-test-config
#
compile;atomic.f90;;-fdump-tree-original;
compile;depobj.f90;xfail;;
compile;fixed-1.f;;-fdump-tree-original -Wunused-variable;
compile;free-1.f90;;-fdump-tree-original -Wunused-variable;
compile;mixed-1.f;xfail;-fdump-tree-original;
compile;pr102330-1.f90;;-fopt-info-omp-note --param=openacc-privatization=noisy;